// @generated by protobuf-ts 2.9.1 with parameter optimize_code_size
// @generated from protobuf file "mailbox.proto" (package "org.mudahmail.rpc", syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message org.mudahmail.rpc.NotificationRequest
 */
export interface NotificationRequest {
    /**
     * @generated from protobuf field: org.mudahmail.rpc.NotificationType type = 1;
     */
    type: NotificationType;
    /**
     * @generated from protobuf field: int64 timestamp = 2;
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: string dataString = 3;
     */
    dataString: string;
    /**
     * @generated from protobuf field: double dataDouble = 4;
     */
    dataDouble: number;
    /**
     * @generated from protobuf field: int64 dataInteger = 5;
     */
    dataInteger: bigint;
    /**
     * @generated from protobuf field: bytes rawData = 6;
     */
    rawData: Uint8Array;
    /**
     * @generated from protobuf field: bool notification = 7;
     */
    notification: boolean;
}
/**
 * @generated from protobuf message org.mudahmail.rpc.DoorRequestResponse
 */
export interface DoorRequestResponse {
    /**
     * @generated from protobuf field: int64 timestamp = 1;
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: bool success = 2;
     */
    success: boolean;
}
/**
 * @generated from protobuf message org.mudahmail.rpc.DoorLockStatusRequest
 */
export interface DoorLockStatusRequest {
    /**
     * @generated from protobuf field: bool toggleLock = 1;
     */
    toggleLock: boolean;
}
/**
 * @generated from protobuf message org.mudahmail.rpc.BiometricsDeletionResponse
 */
export interface BiometricsDeletionResponse {
    /**
     * @generated from protobuf field: int64 biometricId = 1;
     */
    biometricId: bigint;
    /**
     * @generated from protobuf field: bool success = 2;
     */
    success: boolean;
}
/**
 * @generated from protobuf message org.mudahmail.rpc.BiometricsInfoResponse
 */
export interface BiometricsInfoResponse {
    /**
     * @generated from protobuf field: int64 biometricId = 1;
     */
    biometricId: bigint;
    /**
     * @generated from protobuf field: bytes biometricData = 2;
     */
    biometricData: Uint8Array;
    /**
     * @generated from protobuf field: int64 timestamp = 3;
     */
    timestamp: bigint;
}
/**
 * @generated from protobuf message org.mudahmail.rpc.MailboxStatesRequest
 */
export interface MailboxStatesRequest {
    /**
     * @generated from protobuf field: repeated string clientUuid = 1;
     */
    clientUuid: string[];
}
/**
 * @generated from protobuf message org.mudahmail.rpc.MailboxStatesResponse
 */
export interface MailboxStatesResponse {
    /**
     * @generated from protobuf field: repeated org.mudahmail.rpc.MailboxState states = 1;
     */
    states: MailboxState[];
}
/**
 * @generated from protobuf message org.mudahmail.rpc.MailboxState
 */
export interface MailboxState {
    /**
     * @generated from protobuf field: string deviceUUID = 1;
     */
    deviceUUID: string;
    /**
     * @generated from protobuf field: bool locked = 2;
     */
    locked: boolean;
    /**
     * @generated from protobuf field: bool doorOpen = 3;
     */
    doorOpen: boolean;
    /**
     * @generated from protobuf field: bool online = 4;
     */
    online: boolean;
    /**
     * @generated from protobuf field: double lockedWeight = 5;
     */
    lockedWeight: number;
    /**
     * @generated from protobuf field: double currentWeight = 6;
     */
    currentWeight: number;
    /**
     * @generated from protobuf field: int64 lastReceived = 7;
     */
    lastReceived: bigint;
}
// Proposal: A notification to the server requires a long grpc calls, a bi-di is suitable
// for a use-case where a stream of messages are needed to be sent over simultaneously.
// Headers metadata:
// - Bearer: REQUIRED
// - Device: {uuid} [REQUIRED FOR SERVER]

/**
 * @generated from protobuf enum org.mudahmail.rpc.NotificationType
 */
export enum NotificationType {
    /**
     * @generated from protobuf enum value: DOOR_STATE_OPEN = 0;
     */
    DOOR_STATE_OPEN = 0,
    /**
     * @generated from protobuf enum value: DOOR_STATE_CLOSED = 1;
     */
    DOOR_STATE_CLOSED = 1,
    /**
     * @generated from protobuf enum value: DOOR_LOCKED = 3;
     */
    DOOR_LOCKED = 3,
    /**
     * @generated from protobuf enum value: DOOR_UNLOCKED = 4;
     */
    DOOR_UNLOCKED = 4,
    /**
     * @generated from protobuf enum value: WEIGHT_STATE_UPDATE = 5;
     */
    WEIGHT_STATE_UPDATE = 5,
    /**
     * @generated from protobuf enum value: BIOMETRICS_DELETE = 6;
     */
    BIOMETRICS_DELETE = 6,
    /**
     * @generated from protobuf enum value: BIOMETRICS_ADD = 7;
     */
    BIOMETRICS_ADD = 7,
    /**
     * @generated from protobuf enum value: RPC_LAZY_STARTUP = 8;
     */
    RPC_LAZY_STARTUP = 8
}
// @generated message type with reflection information, may provide speed optimized methods
class NotificationRequest$Type extends MessageType<NotificationRequest> {
    constructor() {
        super("org.mudahmail.rpc.NotificationRequest", [
            { no: 1, name: "type", kind: "enum", T: () => ["org.mudahmail.rpc.NotificationType", NotificationType] },
            { no: 2, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "dataString", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "dataDouble", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "dataInteger", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 6, name: "rawData", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 7, name: "notification", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.NotificationRequest
 */
export const NotificationRequest = new NotificationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DoorRequestResponse$Type extends MessageType<DoorRequestResponse> {
    constructor() {
        super("org.mudahmail.rpc.DoorRequestResponse", [
            { no: 1, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.DoorRequestResponse
 */
export const DoorRequestResponse = new DoorRequestResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DoorLockStatusRequest$Type extends MessageType<DoorLockStatusRequest> {
    constructor() {
        super("org.mudahmail.rpc.DoorLockStatusRequest", [
            { no: 1, name: "toggleLock", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.DoorLockStatusRequest
 */
export const DoorLockStatusRequest = new DoorLockStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BiometricsDeletionResponse$Type extends MessageType<BiometricsDeletionResponse> {
    constructor() {
        super("org.mudahmail.rpc.BiometricsDeletionResponse", [
            { no: 1, name: "biometricId", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.BiometricsDeletionResponse
 */
export const BiometricsDeletionResponse = new BiometricsDeletionResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BiometricsInfoResponse$Type extends MessageType<BiometricsInfoResponse> {
    constructor() {
        super("org.mudahmail.rpc.BiometricsInfoResponse", [
            { no: 1, name: "biometricId", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "biometricData", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.BiometricsInfoResponse
 */
export const BiometricsInfoResponse = new BiometricsInfoResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MailboxStatesRequest$Type extends MessageType<MailboxStatesRequest> {
    constructor() {
        super("org.mudahmail.rpc.MailboxStatesRequest", [
            { no: 1, name: "clientUuid", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.MailboxStatesRequest
 */
export const MailboxStatesRequest = new MailboxStatesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MailboxStatesResponse$Type extends MessageType<MailboxStatesResponse> {
    constructor() {
        super("org.mudahmail.rpc.MailboxStatesResponse", [
            { no: 1, name: "states", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MailboxState }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.MailboxStatesResponse
 */
export const MailboxStatesResponse = new MailboxStatesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MailboxState$Type extends MessageType<MailboxState> {
    constructor() {
        super("org.mudahmail.rpc.MailboxState", [
            { no: 1, name: "deviceUUID", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "locked", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "doorOpen", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "online", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "lockedWeight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "currentWeight", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "lastReceived", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message org.mudahmail.rpc.MailboxState
 */
export const MailboxState = new MailboxState$Type();
/**
 * @generated ServiceType for protobuf service org.mudahmail.rpc.Mailbox
 */
export const Mailbox = new ServiceType("org.mudahmail.rpc.Mailbox", [
    { name: "startEventListener", serverStreaming: true, clientStreaming: true, options: {}, I: NotificationRequest, O: NotificationRequest },
    { name: "testEventListener", options: {}, I: NotificationRequest, O: Empty }
]);
/**
 * @generated ServiceType for protobuf service org.mudahmail.rpc.Server
 */
export const Server = new ServiceType("org.mudahmail.rpc.Server", [
    { name: "getMailboxStates", options: {}, I: MailboxStatesRequest, O: MailboxStatesResponse },
    { name: "setDoorLockStatus", options: {}, I: DoorLockStatusRequest, O: DoorRequestResponse },
    { name: "getBiometricList", serverStreaming: true, options: {}, I: Empty, O: BiometricsInfoResponse },
    { name: "deleteBiometricId", options: {}, I: Empty, O: BiometricsDeletionResponse }
]);
