FROM arm64v8/maven:3-amazoncorretto-17 AS build
WORKDIR /home

COPY client /home/app/client
COPY rpc /home/app/rpc
COPY server /home/app/server
COPY pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package -pl client -am

FROM arm64v8/amazoncorretto:17-alpine

# Install basic package to compile source code
RUN apk add alpine-sdk
# Follow the install guide from creator of pigpio, http://abyz.me.uk/rpi/pigpio/download.html
RUN wget --output-document=download.zip https://github.com/joan2937/pigpio/archive/master.zip \
    # Downloaded content is placed inside specific folder to not be depended of branch naming from repo
    && mkdir download \
    && unzip -d download download.zip \
    && cd /download/* \
    # Fix for compiling on Alpine, https://github.com/joan2937/pigpio/issues/107
    && sed -i -e 's/ldconfig/echo ldconfig disabled/g' Makefile \
    && make \
    && make install

WORKDIR /home

COPY --from=build /home/app/client/target/Client.jar /home

ENTRYPOINT ["java", "-jar", "Client.jar"]