# Note: grpc has some problems building against musl-based operating systems.
#       I have to build pigio on ubuntu/debian based systems in order to make it work
#       with pi4j library.
FROM arm64v8/maven:3-eclipse-temurin-17-focal AS binaries
WORKDIR /home

COPY client /home/app/client
COPY rpc /home/app/rpc
COPY server /home/app/server
COPY pom.xml /home/app

RUN mvn -f /home/app/pom.xml clean package -pl client -am

FROM ubuntu:20.04 as builder

# Install basic package to compile source code
RUN apt-get update && apt-get upgrade && apt install -y make autoconf automake libtool libtool-bin m4 wget libc-bin gzip bzip2 bison g++ git re2c unzip
# Follow the install guide from creator of pigpio, http://abyz.me.uk/rpi/pigpio/download.html
RUN wget --output-document=download.zip https://github.com/joan2937/pigpio/archive/master.zip \
    # Downloaded content is placed inside specific folder to not be depended of branch naming from repo
    && mkdir download \
    && unzip -d download download.zip \
    && cd /download/* \
    && make \
    && make install

FROM eclipse-temurin:17-jre-focal

WORKDIR /home

COPY --from=builder /usr/local /usr/local
COPY --from=binaries /home/app/client/target/Client.jar /home

ENTRYPOINT ["java", "-jar", "Client.jar"]